# Generated by Django 4.2.3 on 2023-07-15 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='name',
            field=models.TextField(max_length=200),
        ),
    ]
